#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import urllib2
import sys

if len(sys.argv) != 3:
    print "args illegal"
    exit(0)

tos = sys.argv[1]
message = sys.argv[2]

tos = tos.split(",")
url = "http://xxxxxx.com/api/send/sms"

item = {}
item["app"] = "std"
item["tos"] = tos
item["content"] = {"msg": message}

req = urllib2.Request(url=url, data=json.dumps(item),headers={"Content-Type": "application/json"})
resp = urllib2.urlopen(req)
resp = resp.read()

print resp