#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import urllib2
import sys

if len(sys.argv) != 4:
    print "args illegal"
    exit(0)

tos = sys.argv[1]
subject = sys.argv[2]
fp = sys.argv[3]

f = open(fp, 'r')
content = f.read()
f.close()

tos = tos.split(",")
url = "http://xxxxxx.com/api/send/mail"

item = {}
item["app"] = "std"
item["tos"] = tos
item["subject"] = subject
item["content"] = {"msg": content}

req = urllib2.Request(url=url, data=json.dumps(item),headers={"Content-Type": "application/json"})
resp = urllib2.urlopen(req)
resp = resp.read()

print resp